#!/bin/bash
# ==============================================================================
# BAMBULAPSE DISTANCE CONFIG SCRIPT INSTALLER
# ==============================================================================

# --- Configuration and Safety Nets ---
set -euo pipefail

# --- Source Shared Functions ---
source "$(dirname "$0")/common.sh"

log_info "Creating the distance configuration utility: 'cfgdistance'..."

# --- Get Project Root ---
PROJECT_ROOT=$(cd "$(dirname "$0")/.." && pwd)

# --- Create the 'cfgdistance' script using a Heredoc ---
tee /usr/local/bin/cfgdistance > /dev/null << EOF
#!/bin/bash
# ==============================================================================
# Distance Sensor Configuration Utility (cfgdistance)
#
# Author: @thidiasr
#
# This utility provides an interactive TUI menu to safely edit hc-sr04 sensor distances
# It detects the currently configured distances and GPIO pins, allowing the user to modify them.
# It updates the configuration files used by the main application.
# ==============================================================================

# --- Configuration and Safety Nets ---
set -e
set -u
set -o pipefail

# --- Global Constants ---
PROJECT_ROOT="$PROJECT_ROOT"
CONFIG_DISTANCE_FILE="\$PROJECT_ROOT/distance_config.h"
CONFIG_GPIO_FILE="\$PROJECT_ROOT/gpio_config.h"

# --- Logging Functions ---
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[0;33m'
COLOR_RED='\033[0;31m'
COLOR_RESET='\033[0m'
log_info() { echo -e "\${COLOR_YELLOW}[INFO] \$1\${COLOR_RESET}"; }
log_success() { echo -e "\${COLOR_GREEN}[SUCCESS] \$1\${COLOR_RESET}"; }
log_error() { echo -e "\${COLOR_RED}[ERROR] \$1\${COLOR_RESET}" >&2; exit 1; }

# --- Pre-flight Checks ---
if [ "\$(id -u)" -ne 0 ]; then
    log_error "This script must be run with sudo.";
fi
if [ ! -d "\$PROJECT_ROOT/src" ]; then
    log_error "Source directory not found at '\$PROJECT_ROOT/src'."
fi

# --- Core Functions ---
load_current_values() {
    if [ -r "\$CONFIG_DISTANCE_FILE" ]; then
        local snap_val=\$(grep '#define SNAPSHOTDISTANCE' "\$CONFIG_DISTANCE_FILE" | awk '{print \$3}' | sed 's/f\$//')
        local reset_val=\$(grep '#define RESETDISTANCE' "\$CONFIG_DISTANCE_FILE" | awk '{print \$3}' | sed 's/f\$//')
        local pause_val=\$(grep '#define PAUSESECS' "\$CONFIG_DISTANCE_FILE" | awk '{print \$3}' | sed 's/f\$//')
        if [ -n "\$snap_val" ]; then SNAPSHOT_DISTANCE="\$snap_val"; fi
        if [ -n "\$reset_val" ]; then RESET_DISTANCE="\$reset_val"; fi
        if [ -n "\$pause_val" ]; then PAUSE_SECS="\$pause_val"; fi
    fi
    if [ -r "\$CONFIG_GPIO_FILE" ]; then
        local trig_val=\$(grep '#define TRIG' "\$CONFIG_GPIO_FILE" | awk '{print \$3}')
        local echo_val=\$(grep '#define ECHO' "\$CONFIG_GPIO_FILE" | awk '{print \$3}')
        if [ -n "\$trig_val" ]; then GPIOTRIG="\$trig_val"; fi
        if [ -n "\$echo_val" ]; then GPIOECHO="\$echo_val"; fi
    fi
}

save_config_files() {
    log_info "Saving new values to configuration files..."
    {
        echo "// Auto-generated by cfgdistance"
        printf "#define SNAPSHOTDISTANCE %.1ff\n" "\$SNAPSHOT_DISTANCE"
        printf "#define RESETDISTANCE %.1ff\n" "\$RESET_DISTANCE"
        printf "#define PAUSESECS %.1ff\n" "\$PAUSE_SECS"
    } > "\$CONFIG_DISTANCE_FILE"

    {
        echo "// Auto-generated by cfgdistance"
        echo "#define TRIG \$GPIOTRIG"
        echo "#define ECHO \$GPIOECHO"
    } > "\$CONFIG_GPIO_FILE"
    
    log_success "Configuration files updated successfully."
}

# --- Input Validation ---
is_valid_float() { [[ "\$1" =~ ^[0-9]+(\.[0-9]+)?\$ ]]; }
is_valid_gpio_pin() { [[ "\$1" =~ ^[0-9]+$ ]]; }

# --- Main Menu Loop ---
load_current_values

while true; do
    clear
    echo "===== Sensor Distance & GPIO Configuration ====="
    echo " 1) Snapshot Distance (cm) : \$SNAPSHOT_DISTANCE"
    echo " 2) Reset Distance (cm)    : \$RESET_DISTANCE"
    echo " 3) Pause to snapshot (s)    : \$PAUSE_SECS"
    echo " 4) GPIO TRIG Pin (WiringPi): \$GPIOTRIG"
    echo " 5) GPIO ECHO Pin (WiringPi): \$GPIOECHO"
    echo "----------------------------------------------"
    echo " S) Save and Exit"
    echo " Q) Quit Without Saving"
    echo "=============================================="
    read -p "Select an option: " -n 1 -r OPTION; echo

    case \$OPTION in
        [sS])
            save_config_files
            echo ""
            exit 0
            ;;

        1) read -p "Enter new snapshot distance (e.g., 4.5): " val; if is_valid_float "\$val"; then SNAPSHOT_DISTANCE=\$val; else log_info "Invalid input. Please enter a positive number." && sleep 2; fi;;
        2) read -p "Enter new reset distance (e.g., 7.0): " val; if is_valid_float "\$val"; then RESET_DISTANCE=\$val; else log_info "Invalid input. Please enter a positive number." && sleep 2; fi;;
        3) read -p "Enter new pause time in seconds (e.g., 1.2): " val; if is_valid_float "\$val"; then PAUSE_SECS=\$val; else log_info "Invalid input. Please enter a valid pin number." && sleep 2; fi;;
        4) read -p "Enter new GPIO TRIG pin (WiringPi number): " val; if is_valid_gpio_pin "\$val"; then GPIOTRIG=\$val; else log_info "Invalid input. Please enter a valid pin number." && sleep 2; fi;;
        5) read -p "Enter new GPIO ECHO pin (WiringPi number): " val; if is_valid_gpio_pin "\$val"; then GPIOECHO=\$val; else log_info "Invalid input. Please enter a valid pin number." && sleep 2; fi;;
        [qQ]) log_info "Exiting without saving changes."; exit 0;;
        *) log_info "Invalid option." && sleep 1;;
    esac
done
EOF

# Set execute permission for the newly created utility
chmod +x /usr/local/bin/cfgdistance
log_success "'cfgdistance' utility has been created successfully."
